export const LINK_HOME = '/'
export const LINK_DASHBOARD = '/dashboard'
export const LINK_ANALYSER = '/dashboard/analyser'
export const LINK_RESULT = '/dashboard/result'
export const LINK_PREVIOUS_RECORDS = '/dashboard/previous'
export const LINK_PRIVACY_POLICY = '/privacy-policy'
export const LINK_TOS = '/terms-of-service'
