export default function TermsOfServicePage() {
	return (
		<div className='min-h-screen bg-gray-100 p-4 sm:p-6 lg:p-8 flex justify-center items-start'>
			<div className='max-w-4xl mx-auto w-full bg-white shadow-xl rounded-lg p-6 sm:p-8'>
				<h1 className='text-4xl font-bold text-gray-800 mb-8 text-center border-b pb-4'>
					{'Med Assist App - Terms of Service'}
				</h1>

				<p className='text-sm text-gray-600 mb-6 text-center'>
					{'**Last Updated:** June 25, 2025'}
				</p>

				<section className='space-y-6 text-gray-700 leading-relaxed'>
					<p>
						{
							'Welcome to Med Assist! These Terms of Service ("Terms") govern your access to and use of the Med Assist website and mobile applications (collectively, the "Service"), provided by Med Assist ("we," "us," or "our").'
						}
					</p>
					<p>
						{
							'By accessing or using the Service, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, please do not use the Service.'
						}
					</p>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'1. Acceptance of Terms'}
					</h2>
					<p>
						{
							'By creating an account, accessing, or using the Med Assist Service, you represent that you have read, understood, and agree to be bound by these Terms. We reserve the right to update or modify these Terms at any time without prior notice. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.'
						}
					</p>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'2. Description of Service'}
					</h2>
					<p>
						{
							'Med Assist is a web application designed to help users identify medicine strips using image analysis (Optical Character Recognition - OCR and Large Language Models - LLM) and retrieve general information about the identified medications. The Service allows you to:'
						}
					</p>
					<ul className='list-disc list-inside ml-4 space-y-1'>
						<li>{'Upload images of medicine strips for analysis.'}</li>
						<li>
							{
								'Receive an identified medicine name and a confidence probability.'
							}
						</li>
						<li>
							{
								'Access detailed information about identified medicines (e.g., common name, brands, uses, side effects, price).'
							}
						</li>
						<li>{'View a personalized history of your scanned medicines.'}</li>
					</ul>
					<p className='font-bold text-red-700 mt-4'>
						{
							'Important Disclaimer: The information provided by the Med Assist App is for **general informational purposes only** and is generated by an AI model. **It is NOT medical advice, diagnosis, or treatment.** Always consult with a qualified healthcare professional (doctor, pharmacist, or other medical provider) for any health concerns or before making any decisions related to your health or medication. Do not rely on information from this app to replace professional medical advice.'
						}
					</p>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'3. User Accounts and Registration'}
					</h2>
					<ul className='list-disc list-inside ml-4 space-y-1'>
						<li>
							<strong>{'Account Creation:'}</strong>{' '}
							{
								'To access certain features of the Service, you must create an account using supported third-party authentication providers (e.g., Google, GitHub) via NextAuth.js.'
							}
						</li>
						<li>
							<strong>{'Accuracy of Information:'}</strong>{' '}
							{
								'You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.'
							}
						</li>
						<li>
							<strong>{'Account Security:'}</strong>{' '}
							{
								'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account. We cannot and will not be liable for any loss or damage arising from your failure to comply with this security obligation.'
							}
						</li>
						<li>
							<strong>{'Eligibility:'}</strong>{' '}
							{
								'You must be at least 13 years old to use the Service. If you are under 18, you must have the permission of a parent or guardian.'
							}
						</li>
					</ul>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'4. User Responsibilities'}
					</h2>
					<p>
						{
							'You agree to use the Service only for lawful purposes and in a manner that does not infringe the rights of, or restrict or inhibit the use and enjoyment of the Service by, any third party. Specifically, you agree that you will not:'
						}
					</p>
					<ul className='list-disc list-inside ml-4 space-y-1'>
						<li>
							{
								'Upload any images containing sensitive personal information, offensive content, or copyrighted material without permission.'
							}
						</li>
						<li>
							{
								'Use the Service to transmit any unsolicited or unauthorized advertising, promotional materials, or any other form of solicitation.'
							}
						</li>
						<li>
							{
								'Interfere with or disrupt the integrity or performance of the Service or data contained therein.'
							}
						</li>
						<li>
							{
								'Attempt to gain unauthorized access to the Service or its related systems or networks.'
							}
						</li>
						<li>{'Use the Service to provide or solicit medical advice.'}</li>
						<li>{'Misrepresent your identity or affiliations.'}</li>
					</ul>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'5. Intellectual Property'}
					</h2>
					<ul className='list-disc list-inside ml-4 space-y-1'>
						<li>
							<strong>{'Our Content:'}</strong>{' '}
							{
								'All content, features, and functionality on the Service (including but not limited to text, graphics, logos, icons, images, and software) are the exclusive property of Med Assist or its licensors and are protected by copyright, trademark, and other intellectual property laws.'
							}
						</li>
						<li>
							<strong>{'Your Content:'}</strong>{' '}
							{
								'By uploading images or other content to the Service, you grant us a worldwide, non-exclusive, royalty-free, transferable, and sublicensable license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content in connection with the operation of the Service. You represent and warrant that you own or have the necessary rights to grant us this license.'
							}
						</li>
					</ul>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'6. Privacy Policy'}
					</h2>
					<p>
						{
							'Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by this reference. Please review our Privacy Policy at [Link to your Privacy Policy, e.g., yoursite.com/privacy] to understand our practices regarding the collection, use, and disclosure of your personal information.'
						}
					</p>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'7. Termination'}
					</h2>
					<p>
						{
							'We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms. Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may do so by contacting us.'
						}
					</p>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'8. Limitation of Liability'}
					</h2>
					<p>
						{
							'To the fullest extent permitted by applicable law, in no event shall Med Assist, its affiliates, directors, employees, or licensors be liable for any indirect, punitive, incidental, special, consequential, or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data, or other intangible losses, arising out of or relating to your use of, or inability to use, the Service.'
						}
					</p>
					<p className='font-bold text-red-700 mt-2'>
						{
							'Specifically, we are not liable for any health-related outcomes, adverse reactions, or incorrect decisions made based on information provided by the Service. Your reliance on any information provided by the Service is solely at your own risk.'
						}
					</p>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'9. Indemnification'}
					</h2>
					<p>
						{'You agree to indemnify, defend, and hold harmless ' +
							'Med Assist' +
							" and its affiliates, officers, directors, employees, and agents from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys' fees) that such parties may incur as a result of or arising from your (or anyone using your account's) violation of these Terms or your use of the Service."}
					</p>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'10. Governing Law'}
					</h2>
					<p>
						{
							'These Terms shall be governed by and construed in accordance with the laws of Alipore - kolkata, West Bengal, India without regard to its conflict of law provisions.'
						}
					</p>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'11. Changes to Terms'}
					</h2>
					<p>
						{
							"We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms."
						}
					</p>

					<h2 className='text-2xl font-semibold text-indigo-700 pt-4 pb-2 border-b'>
						{'12. Contact Information'}
					</h2>
					<p>
						{
							'If you have any questions about these Terms, please contact us at:'
						}
					</p>
					<ul className=' list-inside ml-4 space-y-1'>
						<li>{'work.sanwar.hussain@gmail.com'}</li>
					</ul>
				</section>
			</div>
		</div>
	)
}
